apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260516-200212-9djebl0sqgll-service
spec:
  selector:
    app: enterprise-system-20260516-200212-9djebl0sqgll
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
